### ISSUE TITLE
Deposit of ERC223 tokens fail "Bad jump destination"

### ISSUE THREAD

**Issue by Sajjon** [forkdelta/classic-frontend#150]
Hi, currently deposit of ERC223 tokens fails.

What needs to be done in order to support this?

**Comment by freeatnet** [comment]
Need to change the trading smart contract. It's in the plans.

**Comment by Sajjon** [comment]
@freeatnet Okay thank you, can you give any *rough estimate* when the update of the smart contract will happen? Maybe during the summer? The fall?

Thanks!

**Comment by freeatnet** [comment]
Preliminary time is this summer.
