### ISSUE TITLE
Deposit of RiseCoinToken - RSCT fails with Bad Jump Destination error

### ISSUE THREAD

**Issue by anwarsquarebiz** [forkdelta/classic-frontend#153]
When I tried to deposit RiseCoinToken RSCT the balance is more than 50,000 RSCT and I tried to deposit 10,000 RSCT still its not happening.
When I tried depositing it created 2 transaction 1st to RSCT contract and the other to etherdelta_2 contract.
The first transaction is approved which is to RSCT contract and RSCT approved it however etherdelta contract showed an exception.
Below are the same.

Kindly advise if this is a problem with exchange or RSCT contract because I am able to transfer RSCT to some other wallets but not on etherdelta and forkdelta. Just to tell you it is not listed on etherdelta or forkdelta. Is it because of that?

1st.
https://etherscan.io/tx/0xae7a79f815d767f5c96fd5f189ad93aea5b9d75d20d1358551eb1e605145b595
2nd.
https://etherscan.io/tx/0xb9474830bfc1d95069f3245b3c67f0e085bc4c699fd0cc759782af7e5f088eb4

**Comment by freeatnet** [comment]
@anwarsquarebiz Thank you for your report. I noticed that there are a few successful approvals for the current trading contract, but no successful transfers. I was unable to track down the exact issue, I would recommend reaching out to the token issuer for a more thorough investigation.
