### ISSUE TITLE
Websocket, Authentication failed; no valid credentials available

### ISSUE THREAD

**Issue by selimakpnar** [forkdelta/classic-frontend#169]
We installed forkdelta on this adress 142.93.171.46 but some sections are not displaying. If you review the page, on console you will see there are Webscoket warnings.

WebSocket connection to 'wss://backend.bitox.io/socket.io/?EIO=3&transport=websocket' failed: HTTP Authentication failed; no valid credentials available

Can't figure out why its not working. We installed backend to with dockers.

**Comment by alibaraneser** [comment]
+1

**Comment by freeatnet** [comment]
@selimakpnar @alibaraneser backend's `ALLOWED_ORIGIN_SUFFIXES` need to be adjusted to your own configuration. See https://github.com/forkdelta/backend-replacement/blob/master/default.production.env#L15.

**Comment by alibaraneser** [comment]
Hi @freeatnet 

I added ethereum parity node, but there is a error in console.

WebSocket connection to 'ws://127.0.0.1/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Pls help me :(
