### ISSUE TITLE
Metamask transactions not propagated

### ISSUE THREAD

**Issue by leafcutterant** [forkdelta/classic-frontend#172]
Any transactions I submit through Metamask don't show up in the mempool as pending. Metamask thinks they are submitted. Essentially, I can't control funds within Forkdelta.

Why could this be?

**Comment by freeatnet** [comment]
Sorry to hear about your trouble! Sounds like a case of https://github.com/MetaMask/metamask-extension/issues/2271. Consider checking in with the MetaMask support.

Let me know if there's anything else I can help with.
