### ISSUE TITLE
Default Ledger Derivation Path is Wrong

### ISSUE THREAD

**Issue by woodydeck** [forkdelta/classic-frontend#180]
Ledger Live now uses the derivation path m/44'/60'/0'/0, however, ForkDelta uses m/44'/60'/0'. This means you need to send to an unsupported derivation path if you uses your Ledger HW to trade on ForkDelta.

There should be an option for the legacy derivation path. Another solution would be supporting MetaMask, as it now defaults to m/44'/60'/0'/0 for the Ledger Nano S.

Edit: It appears MetaMask works in some browsers, through I haven't had luck in Chrome, all is good on Brave.

**Comment by freeatnet** [comment]
@woodydeck ForkDelta has always supported MetaMask. If you have any issues with MetaMask, please let me know.
